services:
  counter:
    build:
      context: ./counter_express
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    volumes:
      - ./counter_express/src:/app
      - /app/node_modules
    environment:
      - PORT=3001

  express_app:
    build:
      context: ./express
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - URLDB=mongodb://root:example@mongo:27017/mydatabase?authSource=admin
    depends_on:
      mongo:
        condition: service_healthy

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh -u root -p example --quiet || exit 1
      interval: 5s
      timeout: 5s
      retries: 5

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false
